# Generated by Django 4.2 on 2023-04-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='published',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
